### ISSUE TITLE
Current Bugs on Master Branch (commit 8e3284ab2f016970d269d8c98b30e8361ef321c7)

### ISSUE THREAD

**Issue by aaronchu415** [yockelle/CardsAgainstHumanity.github.io#10]
**1. Custom Card Page:** 
_What:_ custom cards are only created for the user who presses the submit last 

_Solution:_ We need to append to the array.txt file instead. Currently the file is getting overwritten as each player submits their custom cards. 

**2. Lobby Page:**
_What:_ Currently only 2 people can join a game at once. If a third player once to join, the game will say it is full. We should allow for more than 2 players.

**3. Resetting game Button // Custom Card Page**
_What:_ Resetting the game will not reset the custom card page. 
1. Ready button is still stuck at "waiting for players" instead of resetting to "ready"
2. All the custom cards that was inputted in the previous round reappears after a user inputs a new custom card. 

_Solution:_
1. We need to reset the custom card page upon reset button click.
2. We need to reset the custom cards and also delete the old custom card.txt file

**Comment by kcheeeung** [comment]
Item 1. I was aware of this, and we can change it to append to file instead. The code actually opens a new file every time so everything is overwritten.
Item 2. It's set to 2 players so it's easy to test, but we can change it.

**Comment by kcheeeung** [comment]
Should be fixed
