### ISSUE TITLE
Unstable socket connection and disconnection

### ISSUE THREAD

**Issue by odoland** [yockelle/CardsAgainstHumanity.github.io#3]
One tab will connect and disconnect. So the socket.id is going to keep changing!

I left one tab logged in idle for 5 minutes:
![screenshot 2018-11-15 18 05 06](https://user-images.githubusercontent.com/20232292/48593328-17e62d00-e901-11e8-98bf-0f6de926e12a.png)

It changes in the middle of connecting to MongoDB too! So how will the server know which socket to emit back to? (See highlighted, and then disconnection right after)

![screenshot 2018-11-15 18 12 58](https://user-images.githubusercontent.com/20232292/48593660-9ee7d500-e902-11e8-9b30-67d7b354bf57.png)

**Comment by odoland** [comment]
I think the reason why server couldn't emit back to the original socket sent was because it lost the connection with it (see above)

In the server.js file - within the newConnection under the insertNewUser() 
If you swap the 
``` 
socket.emit('Registration_Status', result);
```
with
```
socket.broadcast.emit('Registration_Status', result);
```
so that it broadcasts it to all sockets then the client can receive it

![screenshot 2018-11-15 18 23 26](https://user-images.githubusercontent.com/20232292/48594023-03576400-e904-11e8-9833-96c6a8d2c5a8.png)

Maybe this can be of use:
https://stackoverflow.com/questions/26874189/node-js-and-socket-io-client-getting-disconnected-during-request

or if there is a way to somehow find the same client again even after the socket disconnects:
https://socket.io/docs/emit-cheatsheet/

**Comment by aaronchu415** [comment]
We need to prevent the page from reconnecting. Fixed by adding the suggestions below!

https://stackoverflow.com/questions/7803814/prevent-refresh-of-page-when-button-inside-form-clicked

https://stackoverflow.com/questions/30088119/socket-io-app-always-refreshes-on-submit
